language: ruby
rvm:
- 2.2.2
before_script:
- chmod +x ./script/deploy-gh
script: "./script/deploy-gh"
branches:
  only:
  - gh-pages
env:
  global:
  - GH_USERNAME=mayarichman
  - GH_OWNER=the-engine-room
  - GH_REPO=2016-retro
  - GH_REF=github.com/the-engine-room/2016-retro.git
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: GK4X+PfJ0H23OscKwOM9CcVCKSGaQgOxS6vf1mTdJ/ru9EMIxIaxsVEF2i1fuWyMnzvQKXVOFMj+UQ/ChsLRDefFLfCzkz0cxtVDfIz0kZSpiNbnj4X5rBS7jdJD3b+gNT2FsFGepqnzRnA0dbnAqlCuLyiKt2AIvR07fSW9JM2kn7xJC6kkSO9QRl+bKlEVy814PjJRCjAGeFqdSCDNsogtxfmTmWDlajmTPofSx3F1f2jNowwoxPrmODQ0RfcgeYQr6QSAk4ESHCZZUGz6ecAvbwURBjXYpzQR/rHFU9dTRULQEtHtLIMU5Mt8s6f2iZkzpZXfKo+WbC+ol1gH06F9a+UbXeIrFFtatwYzNZPZNXSpEb5f18bEYI9WWcFebMOAyqnD1QsosQdkzPMQw5T004S0AHti9ItMSbItjHYmK3w7CacUkWB7cwYO2PnGr8imQ6YNiJpKB1h9OGOJR4aanDpKOoKxdpY2LkvymmlGFsNidkxNbPDe2McyUumaU3mLsbOHCo+3cAQ76NryMahBYyNdEqkN29MjeJLWgUBtujp3Ne+8iRZfw8TD7d2ywsx9bY0BqwblywbWLQ6TEyaKsygG6HaYmlYonZBNt3CIdwvpG2I9+ovmWWoZZOaklbOuyzGiz16slkZhj1ZqGesg5FWb3NOJl6pEmVctlgc=
sudo: false
notifications:
  slack:
    secure: jIzZqhtQnd7m9gedYto+9vvBpSp1MO2vdHO2GnXM1WS+05mlmzFzAdMnxybDNvevdoFrienu+RmPNT1sNHckwjNA6n+jK+StrqlQgOfkToBXwuz2nE9mmzSRb2jxE31fii4yxAvob/HVUYqqTH/jjIQoYZ/HQ+inxiAV1kO048eaUsFBnC9y1/5J0voAX3ra0Uzft6IVytlD+VwzfDtyVIvozHhI1/cQzQsFjKCDK/1EZO5x6VnCJzcO+rpjqSrX9sSrZUgzkmcbSb2oH5QRlSbKgUizGvSbA69wcUjMkKOIZDOZr4PFH793DoItnZ+ca7tmQkGC2JnhNtFf+t/SckmMwTJmhE7Ihzqc0J18IREXJiywmtzCKwXoosxw2Q7uTGefDhVop2M2hAPoAsH6fSVe/AHsNMHPBx53b+p0H9ovAso5LNcp6BGN/sRTFoJlehdjzKieFTVIuJSn1R/Uo+BcGbHEgSvaNkjCosW42vUvzKdV0xLWQCOGBU1044lq9fX4AL8J8PHubSYooH/pHay0zZAqDe4/VBSWJKnlmOt9uTKENzv8B6Q11bwYWcWJcMCyr1zNNxsPLl1B4L5IYCKjbVF7RYi9trGrynQ5DulJOKsvNwS5KjHfoMdETe98qcmIT6GutoZ+gGSswuUU3xpvJbxJDBLSIkt/vLcAf/A=
