language: ruby
rvm:
- 2.2.2
before_script:
- chmod +x ./script/deploy-gh
script: "./script/deploy-gh"
branches:
  only:
  - gh-pages
env:
  global:
  - GH_USERNAME=mayarichman
  - GH_OWNER=the-engine-room
  - GH_REPO=2016-retro
  - GH_REF=github.com/the-engine-room/2016-retro.git
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: LfQ2uJ08qwozLsa1nt6j/ckdkTNRu/wYYqEFxLwF15jiDL42/gIL6qDY/j9S0ZUEVZ/rsd5PdMWqynOOQoP1t8d3qZ8SSdX/jvlKLJcIAuMV8w2QbT6lzh4AEj3yDwoKqzzF4we5e6gxCyh0J3csd3LLhHz6CUJSKr3Ax6gQBi0AtFfjUKDC8Io5H/r+OMGXaGL6FV3+JOZSaYa9JH9XLE7XmzLx8gk8U/gVXaW/fapkwHM6BkMV4RbIINXzyOcV2ERoMJqnU3tAkgelJF5q077N+xluicTTIY9usha0b0pJ75MvggdjFlLO8gvJba0m4aPwc3/HyluHIahQ3n/0hH47Y/j77Xr8PZAayUuowy0ywpluzkrLSZY5SQKgs+wjxZf7qMLxudQYE9yyU43O+JEHWTDcXL1grOuTINZdVu/Z47WJJk2V3km3ogO7YSuEmXEJZG4031tUPa3SVYdIU/NtzJiEECnrzPCTqZ3dT+ryRlK1dWS7F4FL5VjFrp5cvwaIRNstSiLP33gjS5agS8JglqJyMjZrWQB6G8CTy9nu/ellLIybPm9CoXgua0tJZ9O2NoDjI6A/QnJkRLEvI/8/V7dGSsKR4WglaHhQwwMe2bkvn5+XAGfnDUHz62sDZq/OloDRpiBvlkzTPB89Wb2pZMeTfISEIT2Z4ok4xHk=
sudo: false
notifications:
  slack:
    secure: jIzZqhtQnd7m9gedYto+9vvBpSp1MO2vdHO2GnXM1WS+05mlmzFzAdMnxybDNvevdoFrienu+RmPNT1sNHckwjNA6n+jK+StrqlQgOfkToBXwuz2nE9mmzSRb2jxE31fii4yxAvob/HVUYqqTH/jjIQoYZ/HQ+inxiAV1kO048eaUsFBnC9y1/5J0voAX3ra0Uzft6IVytlD+VwzfDtyVIvozHhI1/cQzQsFjKCDK/1EZO5x6VnCJzcO+rpjqSrX9sSrZUgzkmcbSb2oH5QRlSbKgUizGvSbA69wcUjMkKOIZDOZr4PFH793DoItnZ+ca7tmQkGC2JnhNtFf+t/SckmMwTJmhE7Ihzqc0J18IREXJiywmtzCKwXoosxw2Q7uTGefDhVop2M2hAPoAsH6fSVe/AHsNMHPBx53b+p0H9ovAso5LNcp6BGN/sRTFoJlehdjzKieFTVIuJSn1R/Uo+BcGbHEgSvaNkjCosW42vUvzKdV0xLWQCOGBU1044lq9fX4AL8J8PHubSYooH/pHay0zZAqDe4/VBSWJKnlmOt9uTKENzv8B6Q11bwYWcWJcMCyr1zNNxsPLl1B4L5IYCKjbVF7RYi9trGrynQ5DulJOKsvNwS5KjHfoMdETe98qcmIT6GutoZ+gGSswuUU3xpvJbxJDBLSIkt/vLcAf/A=
